### ISSUE TITLE
Proposal :  s2i-compose

### ISSUE THREAD

**Issue by abdennour** [openshift/source-to-image#1063]
Declarative programming & CoC ( convention over configuration) is already the way.

- Dockerfile is the declarative definition of new image.
- docker-compose is the declarative definition of container runtime
- s2i is the declarative definition of build/runtime process.

However, running s2i itself requires extra arguments : builder image, code, runtime image, build-args,... so on.

The proposal is about having BuildConfig, but that it can run locally with podman or docker .

It must look like as following: 

```yaml
version: '3.7'  

services:
   app:
      build:
         context: myapp/
         builder_image: centos/python-35-centos7
      ports:
        - 5000:5000
      image: hello-python
```

Assume this file is named `s2i-compose.yaml` and exist under this git repo https://github.com/sclorg/django-ex centos/python-35-centos7".
That time, this YAML file should be alternative of this long command: 

```sh
s2i https://github.com/sclorg/django-ex centos/python-35-centos7 hello-python --context-dir=myapp
```
