### ISSUE TITLE
External image input source destinationDir is lost when a contextDir is set

### ISSUE THREAD

**Issue by jfdenise** [openshift/source-to-image#1091]
I am using Openshift sandbox version 4.10.11

When a contextDir is set, the external image content is lost. 
I have the following:
```
build:
  uri: https://github.com/jfdenise/eap-offline-example.git
  ref: main
  contextDir: foo
  images:
    - from:
        kind: ImageStreamTag
        name: 'eap-maven-repo:latest'
      paths:
        - sourcePath: /maven-repository
          destinationDir: ./eap-maven-repo
```
The directory `/tmp/src` doesn't contain the directory `eap-maven-repo`.

If `contextDir` is not used, then the `eap-maven-repo` is properly copied to `/tmp/src`.

I am not able to find a workaround. help would be greatly appreciated.
Thank-you.
