### ISSUE TITLE
BuildConfig with dockerStrategy : there is no POM in this directory

### ISSUE THREAD

**Issue by dahuchao** [openshift/source-to-image#920]
I am making a build config with a docker Strategy but it does not work.

Template YALM of my BuildConfig

```
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: bc-${CC}-${TM}
      namespace: ${CC}-${ENV}
      labels:
        ccxtm: ${CC}-${TM}
    spec:
      source:
        type: Git
        git:
          ref: ${GITBRANCH}
          uri: ${GITURL}
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            namespace: openshift
            name: ${ImageStreamTag}
      output:
        to:
          kind: ImageStreamTag
          namespace: ${CC}-${ENV}
          name: 'is-${CC}-${TM}:latest'
```

My Dockerfile
```
FROM redhat-openjdk18-openshift:1.2-6

ENV JAVA_HOME=/opt/run-java
ENV MAVEN_HOME=/opt/rh/rh-maven33/root/usr/share/maven/bin

RUN ${MAVEN_HOME}/mvn clean package -Dmaven.test.skip=true

COPY target/*.jar /deployments

EXPOSE 8080

CMD ${JAVA_HOME}/run-java.sh
```

The result 

```
[INFO] Scanning for projects...
[INFO] BUILD FAILURE
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/jboss). Please verify you invoked Maven from the correct directory. -> [Help 1]
```
